"""dd poster_path to ovie and profile_path to ctor

Revision ID: 003deb93760c
Revises: 1f1f1574be2b
Create Date: 2025-12-09 18:17:51.497582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003deb93760c'
down_revision: Union[str, Sequence[str], None] = '1f1f1574be2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('profile_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'profile_path')
    # ### end Alembic commands ###
