"""Add MediaType Enum and refine Movie model

Revision ID: 1ad95bbaa0c3
Revises: 9e45d0973149
Create Date: 2025-12-07 20:03:29.303187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad95bbaa0c3'
down_revision: Union[str, Sequence[str], None] = '9e45d0973149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
