"""dd poster_path to ovie and profile_path to ctor

Revision ID: 1f1f1574be2b
Revises: b99ea8ea3ab2
Create Date: 2025-12-09 18:00:55.204632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f1f1574be2b'
down_revision: Union[str, Sequence[str], None] = 'b99ea8ea3ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('poster_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'poster_path')
    # ### end Alembic commands ###
