"""Add MediaType Enum and refine Movie model

Revision ID: 3c3afe771349
Revises: 46f7e425e0ef
Create Date: 2025-12-07 16:25:16.944000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c3afe771349'
down_revision: Union[str, Sequence[str], None] = '46f7e425e0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    media_type_enum = postgresql.ENUM('movie', 'tv_series', name='mediatype')

    media_type_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('movies', 'media_type',
               existing_type=sa.VARCHAR(),
               type_=media_type_enum,
               existing_nullable=False,
               postgresql_using='media_type::mediatype')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'media_type',
                    existing_type=postgresql.ENUM('movie', 'tv_series', name='mediatype'),
                    type_=sa.VARCHAR(),
                    existing_nullable=False,
                    postgresql_using='media_type::VARCHAR')

    media_type_enum = postgresql.ENUM('movie', 'tv_series', name='mediatype')
    media_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
