"""add_update_date_movies

Revision ID: 8cd3b4f82506
Revises: e098ba40958a
Create Date: 2025-12-17 18:08:05.190696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd3b4f82506'
down_revision: Union[str, Sequence[str], None] = 'e098ba40958a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('update_date_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'update_date_at')
    # ### end Alembic commands ###
