"""Add MediaType Enum and refine Movie model

Revision ID: 9e45d0973149
Revises: 5fcf1eceb4c9
Create Date: 2025-12-07 19:35:16.330063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e45d0973149'
down_revision: Union[str, Sequence[str], None] = '5fcf1eceb4c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
