"""Add MediaType Enum and refine Movie model

Revision ID: b99ea8ea3ab2
Revises: 1ad95bbaa0c3
Create Date: 2025-12-07 20:19:02.509096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b99ea8ea3ab2'
down_revision: Union[str, Sequence[str], None] = '1ad95bbaa0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
