"""add_cascade_delete_to_movies

Revision ID: e098ba40958a
Revises: eb0d292df2ca
Create Date: 2025-12-17 13:51:32.322391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e098ba40958a'
down_revision: Union[str, Sequence[str], None] = 'eb0d292df2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('movie_genres_genre_id_fkey'), 'movie_genres', type_='foreignkey')
    op.drop_constraint(op.f('movie_genres_movie_id_fkey'), 'movie_genres', type_='foreignkey')
    op.create_foreign_key(None, 'movie_genres', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movie_genres', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_genres', type_='foreignkey')
    op.drop_constraint(None, 'movie_genres', type_='foreignkey')
    op.create_foreign_key(op.f('movie_genres_movie_id_fkey'), 'movie_genres', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key(op.f('movie_genres_genre_id_fkey'), 'movie_genres', 'genres', ['genre_id'], ['id'])
    # ### end Alembic commands ###
