"""Add budget, revenue, and production_countries to Movie table

Revision ID: eb0d292df2ca
Revises: 003deb93760c
Create Date: 2025-12-12 18:47:51.342693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0d292df2ca'
down_revision: Union[str, Sequence[str], None] = '003deb93760c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('budget', sa.DECIMAL(precision=20, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'budget')
    # ### end Alembic commands ###
